version: "3"

services:
  postgres:
    image: "postgres:9.5"
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    container_name: hubtec_tasks_api
    hostname: hubtec_tasks_api
#    restart: always
    depends_on:
      - "postgres"
    build:
      context: ./hubtec_tasks_api
      dockerfile: Dockerfile
#    command: bash ./hubtec_tasks_api:/start.sh
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "bundle check || bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    volumes:
      - ./hubtec_tasks_api:/hubtec_tasks_api
      - gems:/gems

  web:
    container_name: hubtec_tasks_front
    hostname: hubtec_tasks_front
#    restart: always
    build:
      context: ./hubtec_tasks_front
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3001:3000"
    volumes:
      - ./hubtec_tasks_front:/hubtec_tasks_front

volumes:
  postgres:
  gems: