version: "3"

services:
  db:
    container_name: db
    image: "postgres:9.5"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - db-network

  app:
    depends_on:
      - db
    build: .
    command: bash start.sh
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/hubtec_tasks_api
      - gems:/gems
    networks:
      - db-network

volumes:
  db:
  gems:


networks:
  db-network:
    driver: bridge
